# Generated by Django 2.0 on 2018-09-20 21:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=12)),
                ('interests', multiselectfield.db.fields.MultiSelectField(choices=[('101', 'Cinema'), ('102', 'Theater'), ('103', 'Musicals'), ('104', 'Concerts'), ('105', 'Festivals'), ('106', 'Sports'), ('107', 'Nightlife'), ('201', 'Museums'), ('202', 'Sightseeing'), ('203', 'Photography'), ('301', 'Adventure'), ('302', 'Congresses & Events'), ('303', 'Nightlife'), ('401', 'Food'), ('402', 'Relax'), ('403', 'Shopping')], default=('101', 'Cinema'), max_length=255)),
                ('confirmed', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
