# Generated by Django 2.0.5 on 2018-05-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regularuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='admin',
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='sex',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=255),
        ),
    ]
